### ISSUE TITLE
Suggestion: clj-refactor and refactor-nrepl

### ISSUE THREAD

**Issue by benedekfazekas** [weavejester/clojure-toolbox.com#120]
https://github.com/clojure-emacs/clj-refactor.el
emacs refactor tool, partly vanilla elisp (no repl needed, works for cljs too) partly uses refactor-nrepl as a backend (same architecture as cider and cider-nrepl)

https://github.com/clojure-emacs/refactor-nrepl
nrepl middleware. mainly clj but some cljs support as well. client agnostic: used by clj-refactor.el, lighttable (via plugin), vim (via plugin)

**Comment by weavejester** [comment]
Fixed in 71b503f0

**Comment by benedekfazekas** [comment]
thx :+1:
