### ISSUE TITLE
Linked Data & RDF Libraries

### ISSUE THREAD

**Issue by RickMoynihan** [weavejester/clojure-toolbox.com#121]
Some suggestions for a Linked Data & RDF section:

- Grafter - http://grafter.org/
- YesSPARQL - https://github.com/joelkuiper/yesparql
- Tawny Owl - https://github.com/phillord/tawny-owl

Full disclosure - I am one of the authors of Grafter.

**Comment by weavejester** [comment]
Fixed in 7cb60ba
