### ISSUE TITLE
Miscategorized yada

### ISSUE THREAD

**Issue by SevereOverfl0w** [weavejester/clojure-toolbox.com#144]
Yada is currently under the RESTful part of the site, however I'd make an argument for it not being only aimed at that. It's more of a web framework than for RESTful apis.

From the current yada docs:
> yada is also agnostic to how you want to build your app. It is designed to be easy to use for HTML content and web APIs, in whatever style you decide is right for you (Swagger documented, hypermedia driven, ROCA, jsonapi, real-time, etc).

Not sure if you feel a move would be important? But would be interested to hear your thoughts.

**Comment by weavejester** [comment]
I could also put it under "Web Frameworks".

**Comment by weavejester** [comment]
Added to "Web Frameworks" in 6cec566f
