### ISSUE TITLE
Should C2 be removed?

### ISSUE THREAD

**Issue by gonewest818** [weavejester/clojure-toolbox.com#216]
The 2D visualization library [C2](https://keminglabs.com/c2/) appears to be [deprecated](https://github.com/lynaghk/c2/commit/c6b51e47d70c18ee3063c083082c654e0db12b7c). Should the link be removed from the site?

**Comment by weavejester** [comment]
Yes, deprecated libraries can be removed. :)

**Comment by gonewest818** [comment]
ok, do you want/need a pull request for this?  :)

**Comment by weavejester** [comment]
Just did it. :)
