### ISSUE TITLE
Submitting Klipse

### ISSUE THREAD

**Issue by viebel** [weavejester/clojure-toolbox.com#249]
What should be the categories for:
- Klipse the [web app](http://app.klipse.tech/)
- Klipse the [plugin](https://github.com/viebel/klipse)

**Comment by weavejester** [comment]
Good question. Maybe "ClojureScript Development" and "Leiningen Plugins" (for the plugin only). Maybe also add a new category "Interactive Development"? Is there another term you think would be more suitable?

**Comment by viebel** [comment]
ClojureScript Development is fine for Klipse the web app.
For Klipse the plugin - a new category "Interactive Development" will be fine.

**Comment by viebel** [comment]
PR submitted. Thanks
