### ISSUE TITLE
Suggestion : kafka.clj

### ISSUE THREAD

**Issue by dvlopt** [weavejester/clojure-toolbox.com#282]
Hi,

This is the only clojure client library for Kafka having pretty much feature parity with the official java libraries and support for Kafka Streams :

https://github.com/dvlopt/kafka.clj

**Comment by AndreaCrotti** [comment]
I've just added another one
https://github.com/FundingCircle/jackdaw/
which also supports streams and it's quite exhaustive

**Comment by dvlopt** [comment]
I am aware of jackdaw. Still, I recommend you have a look at my lib, I believe a lot of things are better organized. In any case, I would be glad to have your opinion since you are familiar with the subject.
