### ISSUE TITLE
Missing project

### ISSUE THREAD

**Issue by dotemacs** [weavejester/clojure-toolbox.com#323]
When looking at the database migration projects, clicked on:

> Database Migrations -> clj-sql-up

Only to find a 404, with not just that project missing, but also the user under which the project is hosted.

Just checked on Clojars and the project is there: https://clojars.org/clj-sql-up

**Comment by steffan-westcott** [comment]
@weavejester I think this issue can be closed, as the reference to `clj-sql-up` was removed by this commit : https://github.com/weavejester/clojure-toolbox.com/commit/666019bbfb2583c201ae9b39841ab96a5c317b60
