### ISSUE TITLE
Certificate of the website is expired

### ISSUE THREAD

**Issue by saitouena** [weavejester/clojure-toolbox.com#377]
https://www.clojure-toolbox.com/

Chromium reports `NET::ERR_CERT_DATE_INVALID`.

**Comment by weavejester** [comment]
Thanks for the report, it should be fixed now. It's strange that the certificate lapsed... something must have gone wrong with the last renewal and didn't notify me.

**Comment by saitouena** [comment]
It's now fixed! Thanks!
