### ISSUE TITLE
Certificate for www.clojure-toolbox.com has expired

### ISSUE THREAD

**Issue by athos** [weavejester/clojure-toolbox.com#436]
According to the warning message from my browser, the certificate for `www.clojure-toolbox.com` expired two days ago:

<img width="500" src="https://user-images.githubusercontent.com/27441/146681405-71078f36-04a3-4dd6-b966-abc8d3ef68ee.png">

**Comment by weavejester** [comment]
Fixed! Looks like the last certificate update didn't work right.
