### ISSUE TITLE
clojure-toolbox.com TLS certificate has expired

### ISSUE THREAD

**Issue by esuomi** [weavejester/clojure-toolbox.com#450]
...since yesterday. Seems it's a LetsEncrypt certificate, so should be easy to renew?

**Comment by weavejester** [comment]
What? Again? That's so weird. Perhaps I should add a reporter to tell me when it fails.

Fixed, anyway.

**Comment by esuomi** [comment]
You could also go the lazy route and just autogenerate and deploy a new certificate every 60 days or so :)

**Comment by weavejester** [comment]
I have automation to do it for me at set intervals, but did you mean something else?

**Comment by esuomi** [comment]
Pretty much exactly that, just make it repeat often enough that this'll never be a problem again. Assuming that's the issue, of course - haven't looked into ACME autorenewal in literally years.

Anyway, it's fixed so I'm happy -> closed :)
