### ISSUE TITLE
Site formatting broken due to incorrect MIME types

### ISSUE THREAD

**Issue by TuggyNE** [weavejester/clojure-toolbox.com#456]
In Firefox and Chrome, CSS served with a mismatched MIME type is blocked, and recently-ish the CSS and JS served from the site instance switched from correct types to the wrong ones, so there is currently no styling. (JS runs correctly, but with a warning.)

**Comment by weavejester** [comment]
Oh, wow, weird. Let me see if I can figure out what caused that.

**Comment by weavejester** [comment]
Looks like it's a bug or change in behaviour of s3cmd. The mime magic is overriding the file extension when it comes to guessing the mime type. Adding the `--no-mime-magic` option forces it to use the extension only.

**Comment by weavejester** [comment]
Oh, and thanks for the report! It's much appreciated!

**Comment by TuggyNE** [comment]
Glad you were able to fix this so quickly! You're welcome for the report :)
