### ISSUE TITLE
Proposal for a few additions to the list

### ISSUE THREAD

**Issue by ghaskins** [weavejester/clojure-toolbox.com#481]
Hi,

First, thank you for all your work in the Clojure space.  I use many of your libraries/frameworks/tools (medley, integrant, environ, etc) in my professional job.

I have authored and maintain a few Clojure tools/libraries myself that I would like to have considered for your clojure-toolbox list.

1. https://github.com/manetu/temporal-clojure-sdk
2. https://protojure.readthedocs.io/en/latest/

I am happy to create a PR against the projects.yml if appropriate.  I didn't want just to do so cold in case there was a different process for consideration, or you are not interested, etc.

Thanks again,

-Greg

**Comment by weavejester** [comment]
Go ahead! I'd welcome a PR.

**Comment by KingMob** [comment]
@ghaskins shouldnt this be closed?

**Comment by ghaskins** [comment]
Indeed, lost in the shuffle
