### ISSUE TITLE
Way to remove unsupported libraries

### ISSUE THREAD

**Issue by edtsech** [weavejester/clojure-toolbox.com#9]
Maybe by a date of the last commit?

**Comment by niwinz** [comment]
Or the date of uncommented issues. 

The two main symptoms if a project is abandoned if issues or PR are not attended, and the date of the last commit.

**Comment by boechat107** [comment]
+1

Abandoned issues and PRs seem reasonable symptoms for me too.

**Comment by magnars** [comment]
Date of uncommented issues sounds fine. Date of last commit is not - sometimes a library is just done. Finished.

**Comment by lianxiangru** [comment]
+1

**Comment by weavejester** [comment]
I think I'll keep this process as manual for now. The site is static anyway, so delisting can only happen offsite anyway.
